LibraryPortal/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;

namespace LibraryPortal.Models
{
    public class Item
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string Author { get; set; }
        public string ItemType { get; set; }
        public ICollection<ItemRequest> ItemRequests { get; set; }
        public ICollection<CheckedOutTable> CheckOuts { get; set; }
    }

}

LibraryPortal/Controllers/ItemsController.cs
using LibraryPortal.HttpHelpers;
using LibraryPortal.Models;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LibraryPortal.Controllers
{
    public class ItemsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [ActionName("list")]
        public async Task<PartialViewResult> List()
        {
            var clientWrapper = new HttpClientWrapper<Item>();
            var items = await clientWrapper.GetItems();
            return PartialView("_table", items);
        }

        public async Task<ActionResult> StudentIndex()
        {
            var clientWrapper = new HttpClientWrapper<Item>();
            var items = await clientWrapper.GetItems();
            return View(items);
        }
        // POST: Items/Create

        [HttpPost]
        [ActionName("create")]
        public async Task<ActionResult> Create(Item item)
        {
            var clientWrapper = new HttpClientWrapper<Item>();
            var items = await clientWrapper.Create(item);
            return Json(true);
        }

        public async Task<ActionResult> Update(int id)
        {
            var clientWrapper = new HttpClientWrapper<Item>();
            var item = await clientWrapper.GetItem(id);
            return View(item);
        }

        [HttpPost]
        public async Task<ActionResult> Update(int id, Item item)
        {
            var clientWrapper = new HttpClientWrapper<Item>();
            await clientWrapper.Update(id, item);
            return RedirectToAction("Index");
        }

        [HttpDelete]
        [ActionName("Delete")]
        // DELETE: api/items/id
        public async Task<ActionResult> Delete(int id)
        {
            var clientDeleteWrapper = new HttpClientWrapper<Item>();
            var item = await clientDeleteWrapper.Delete(id);
            //return View(item);
            return Json(true);
        }

        //other methods

        public ActionResult Details(int id)
        {
            var clientWrapper = new HttpClientWrapper<Item>();
            var item = clientWrapper.GetItem(id);
            return View(item);
        }
    }
}

LibraryPortal/Views/Items/Borrow.cshtml
@{
    ViewBag.Title = "Borrow";
}

<h2>Borrow</h2>

LibraryPortal/Views/Items/Delete.cshtml
@model LibraryPortal.Models.Item

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemType)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryPortal/Views/Items/Details.cshtml
@model LibraryPortal.Models.Item

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LibraryPortal/Views/Items/Index.cshtml
@model List<LibraryPortal.Models.Item>

@{
    ViewBag.Title = "Index";
}

<script type="text/javascript" src="~/Scripts/libraryItems.js"></script>

@Html.Partial("_create", new LibraryPortal.Models.Item())

@*<div style="padding-top: 3px;">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Create New</button>
</div>
    *@



@* Create New Modal *@











@* delete modal *@
<div id="container"></div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <p>Delete</p>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this item?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="btnDelete" data-dismiss="modal">Confirm</button>
            </div>
        </div>
    </div>
</div>





<script type="text/javascript">
    libraryItems.getItems();
    $("#btnDelete").bind("click", libraryItems.deleteItem);
</script>

LibraryPortal/Views/Items/StudentIndex.cshtml
@model IEnumerable<LibraryPortal.Models.Item>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="container">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
            <input type="text" id="Search" placeholder="Search" class="form-control" />
        </div>
    </div>
</div>


<table class="table table-striped">
    <tr>
        <th>
            Book Name
        </th>
        <th>
            Author
        </th>
        <th>
            Type
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr class="Search">
    <td>
        @Html.DisplayFor(modelItem => item.Item_Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Author)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Item_Type)
    </td>
    @*<td>
            @Html.ActionLink("Details", "Details", new { id=item.ItemId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ItemId })
        </td>
    *@
<td>
    @Html.ActionLink("Borrow", "Borrow", new { id = item.ItemId }) 
</td>

</tr>
    }

</table>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script>
    $(document).ready(function () {
        function Contains(first_text, second_text) {
            if (first_text.indexOf(second_text) != -1) {
                return true;
            }
        }
        $("#Search").keyup(function () {
            var boxText = $("#Search").val().toLowerCase();
            $(".Search").each(function () {
                if (!Contains($(this).text().toLowerCase(), boxText)) {
                    $(this).hide();
                } else {
                    $(this).show();
                }
            });
        });
    });
</script>

LibraryPortal/Views/Items/Update.cshtml
@model LibraryPortal.Models.Item

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Update", "Items", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => Model.ItemId)

        <div class="form-group">
            @Html.LabelFor(model => Model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => Model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => Model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => Model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => Model.ItemType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => Model.ItemType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => Model.ItemType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LibraryPortal/Views/Items/_Table.cshtml
@model List<LibraryPortal.Models.Item>


@*<button class="btn btn-default" data-authorid="@item.ItemId" data-toggle="modal" data-target="#deleteModal" onclick="libraryItems.deleteModalDialog(this);">
    Create New
</button>*@


<div style="padding-top: 3px;">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="libraryItems.createModalDialog(this);">Create New</button>
</div>



<table class="table table-striped">
    <thead class="thead-light">
        <tr>
            <th>
                Book Name
            </th>
            <th>
                Author
            </th>
            <th>
                Type
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemType)
                </td>
                <td>
                    @Html.ActionLink("Update", "Update", new { id = item.ItemId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ItemId }) |
                    <button class="btn btn-default" data-authorid="@item.ItemId" data-toggle="modal" data-target="#deleteModal" onclick="libraryItems.deleteModalDialog(this);">
                        Delete
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

LibraryPortal/Views/Items/_create.cshtml
@model LibraryPortal.Models.Item


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

@using (Html.BeginForm("create", "Items", FormMethod.Post))
{
    <div class="container">  
        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        @*<h4 class="modal-title"</h4>*@
                        <h4 class="modal-title w-100 font-weight-bold">Create New</h4>
                    </div>
                    <div class="modal-body">

                        <div class="form-group">
                            <label for=@Model.ItemName>Item's Name:</label>
                            <input id="itemName"
                                   name="item_name"
                                   value=""
                                   class="form-control"
                                   placeholder="Name of Item" />
                        </div>
                        <div class="form-group">
                            <label for=@Model.Author>Author:</label>
                            <input id="itemAuthor"
                                   name="item_author"
                                   value=""
                                   class="form-control"
                                   placeholder="Author of the book" />
                        </div>
                        <div class="form-group">
                            <label for=@Model.ItemType>Type of Item:</label>
                            <input id="itemType"
                                   name="item_type"
                                   value=""
                                   class="form-control"
                                   placeholder="Genre of Book" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" id="btnSave" data-dismiss="modal">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

    <script type="text/javascript">
    libraryItems.getItems();
        $("#btnSave").bind("click", libraryItems.createItem);
    </script>